### test: Enter post title (ERROR)
POST http://localhost:3000/api/posts
Content-Type: application/json

{}

### test: Enter author name (ERROR)
POST http://localhost:3000/api/authors
Content-Type: application/json

{}

### test: Fill all fields (ERROR)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "wrong",
  "password": "wrong"
}

### test: login uspex
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### test: post create
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "Test Post",
  "content": "Test content",
  "authorId": 123,
  "type": "Games"
}

### test: posti
GET http://localhost:3000/api/posts